version: 0.2

#TODO: Move all constatns to environment variables
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - pip install -r src/requirements.txt
      #- bash src/setup.sh $FRAMEWORK
      - python src/parse_partner_developers.py
      #- python src/send_status.py --status 2
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
      - python src/main.py --buildspec $FRAMEWORK_BUILDSPEC_FILE --framework $FRAMEWORK
      - cp $FRAMEWORK_BUILDSPEC_FILE $HOME/framework-buildspec.yml
  post_build:
    commands:
      - echo Build step finished on `date`
      - echo Starting test jobs
      - python src/start_testbuilds.py
      #- python src/send_status.py --status $CODEBUILD_BUILD_SUCCEEDING
artifacts:
  secondary-artifacts:
    DLC_IMAGES_JSON:
      files:
        - $HOME/test_type_images.json
      name: DLC_IMAGES_JSON
      discard-paths: yes
    DLC_BUILDSPEC_FILE:
      files:
        - $HOME/framework-buildspec.yml
      name: DLC_BUILDSPEC_FILE
      discard-paths: yes
